// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.bupt;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string strObj = 1;</code>
     */
    java.lang.String getStrObj();
    /**
     * <code>string strObj = 1;</code>
     */
    com.google.protobuf.ByteString
        getStrObjBytes();

    /**
     * <code>int32 int32Obj = 2;</code>
     */
    int getInt32Obj();

    /**
     * <code>int64 int64Obj = 3;</code>
     */
    long getInt64Obj();

    /**
     * <code>uint32 uint32Obj = 4;</code>
     */
    int getUint32Obj();

    /**
     * <code>uint64 uint64Obj = 5;</code>
     */
    long getUint64Obj();

    /**
     * <code>sint32 sint32Obj = 6;</code>
     */
    int getSint32Obj();

    /**
     * <code>sint64 sint64Obj = 7;</code>
     */
    long getSint64Obj();

    /**
     * <code>fixed32 fixed32Obj = 8;</code>
     */
    int getFixed32Obj();

    /**
     * <code>fixed64 fixed64Obj = 9;</code>
     */
    long getFixed64Obj();

    /**
     * <code>sfixed32 sfixed32Obj = 10;</code>
     */
    int getSfixed32Obj();

    /**
     * <code>sfixed64 sfixed64Obj = 11;</code>
     */
    long getSfixed64Obj();

    /**
     * <code>bool boolObj = 12;</code>
     */
    boolean getBoolObj();

    /**
     * <code>bytes bytesObj = 13;</code>
     */
    com.google.protobuf.ByteString getBytesObj();

    /**
     * <code>float folatObj = 14 [deprecated = true];</code>
     */
    @java.lang.Deprecated float getFolatObj();

    /**
     * <pre>
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     */
    java.util.List<java.lang.Double> getDoubleObjList();
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     */
    int getDoubleObjCount();
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     */
    double getDoubleObj(int index);

    /**
     * <code>.demo.InnerMessage innerMessage = 16;</code>
     */
    boolean hasInnerMessage();
    /**
     * <code>.demo.InnerMessage innerMessage = 16;</code>
     */
    com.bupt.InnerMessageProtos.InnerMessage getInnerMessage();
    /**
     * <code>.demo.InnerMessage innerMessage = 16;</code>
     */
    com.bupt.InnerMessageProtos.InnerMessageOrBuilder getInnerMessageOrBuilder();
  }
  /**
   * Protobuf type {@code demo.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      strObj_ = "";
      int32Obj_ = 0;
      int64Obj_ = 0L;
      uint32Obj_ = 0;
      uint64Obj_ = 0L;
      sint32Obj_ = 0;
      sint64Obj_ = 0L;
      fixed32Obj_ = 0;
      fixed64Obj_ = 0L;
      sfixed32Obj_ = 0;
      sfixed64Obj_ = 0L;
      boolObj_ = false;
      bytesObj_ = com.google.protobuf.ByteString.EMPTY;
      folatObj_ = 0F;
      doubleObj_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              strObj_ = s;
              break;
            }
            case 16: {

              int32Obj_ = input.readInt32();
              break;
            }
            case 24: {

              int64Obj_ = input.readInt64();
              break;
            }
            case 32: {

              uint32Obj_ = input.readUInt32();
              break;
            }
            case 40: {

              uint64Obj_ = input.readUInt64();
              break;
            }
            case 48: {

              sint32Obj_ = input.readSInt32();
              break;
            }
            case 56: {

              sint64Obj_ = input.readSInt64();
              break;
            }
            case 69: {

              fixed32Obj_ = input.readFixed32();
              break;
            }
            case 73: {

              fixed64Obj_ = input.readFixed64();
              break;
            }
            case 85: {

              sfixed32Obj_ = input.readSFixed32();
              break;
            }
            case 89: {

              sfixed64Obj_ = input.readSFixed64();
              break;
            }
            case 96: {

              boolObj_ = input.readBool();
              break;
            }
            case 106: {

              bytesObj_ = input.readBytes();
              break;
            }
            case 117: {

              folatObj_ = input.readFloat();
              break;
            }
            case 121: {
              if (!((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
                doubleObj_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00004000;
              }
              doubleObj_.add(input.readDouble());
              break;
            }
            case 122: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00004000) == 0x00004000) && input.getBytesUntilLimit() > 0) {
                doubleObj_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00004000;
              }
              while (input.getBytesUntilLimit() > 0) {
                doubleObj_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 130: {
              com.bupt.InnerMessageProtos.InnerMessage.Builder subBuilder = null;
              if (innerMessage_ != null) {
                subBuilder = innerMessage_.toBuilder();
              }
              innerMessage_ = input.readMessage(com.bupt.InnerMessageProtos.InnerMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(innerMessage_);
                innerMessage_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
          doubleObj_ = java.util.Collections.unmodifiableList(doubleObj_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bupt.MessageProtos.internal_static_demo_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bupt.MessageProtos.internal_static_demo_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bupt.MessageProtos.Message.class, com.bupt.MessageProtos.Message.Builder.class);
    }

    private int bitField0_;
    public static final int STROBJ_FIELD_NUMBER = 1;
    private volatile java.lang.Object strObj_;
    /**
     * <code>string strObj = 1;</code>
     */
    public java.lang.String getStrObj() {
      java.lang.Object ref = strObj_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        strObj_ = s;
        return s;
      }
    }
    /**
     * <code>string strObj = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStrObjBytes() {
      java.lang.Object ref = strObj_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strObj_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INT32OBJ_FIELD_NUMBER = 2;
    private int int32Obj_;
    /**
     * <code>int32 int32Obj = 2;</code>
     */
    public int getInt32Obj() {
      return int32Obj_;
    }

    public static final int INT64OBJ_FIELD_NUMBER = 3;
    private long int64Obj_;
    /**
     * <code>int64 int64Obj = 3;</code>
     */
    public long getInt64Obj() {
      return int64Obj_;
    }

    public static final int UINT32OBJ_FIELD_NUMBER = 4;
    private int uint32Obj_;
    /**
     * <code>uint32 uint32Obj = 4;</code>
     */
    public int getUint32Obj() {
      return uint32Obj_;
    }

    public static final int UINT64OBJ_FIELD_NUMBER = 5;
    private long uint64Obj_;
    /**
     * <code>uint64 uint64Obj = 5;</code>
     */
    public long getUint64Obj() {
      return uint64Obj_;
    }

    public static final int SINT32OBJ_FIELD_NUMBER = 6;
    private int sint32Obj_;
    /**
     * <code>sint32 sint32Obj = 6;</code>
     */
    public int getSint32Obj() {
      return sint32Obj_;
    }

    public static final int SINT64OBJ_FIELD_NUMBER = 7;
    private long sint64Obj_;
    /**
     * <code>sint64 sint64Obj = 7;</code>
     */
    public long getSint64Obj() {
      return sint64Obj_;
    }

    public static final int FIXED32OBJ_FIELD_NUMBER = 8;
    private int fixed32Obj_;
    /**
     * <code>fixed32 fixed32Obj = 8;</code>
     */
    public int getFixed32Obj() {
      return fixed32Obj_;
    }

    public static final int FIXED64OBJ_FIELD_NUMBER = 9;
    private long fixed64Obj_;
    /**
     * <code>fixed64 fixed64Obj = 9;</code>
     */
    public long getFixed64Obj() {
      return fixed64Obj_;
    }

    public static final int SFIXED32OBJ_FIELD_NUMBER = 10;
    private int sfixed32Obj_;
    /**
     * <code>sfixed32 sfixed32Obj = 10;</code>
     */
    public int getSfixed32Obj() {
      return sfixed32Obj_;
    }

    public static final int SFIXED64OBJ_FIELD_NUMBER = 11;
    private long sfixed64Obj_;
    /**
     * <code>sfixed64 sfixed64Obj = 11;</code>
     */
    public long getSfixed64Obj() {
      return sfixed64Obj_;
    }

    public static final int BOOLOBJ_FIELD_NUMBER = 12;
    private boolean boolObj_;
    /**
     * <code>bool boolObj = 12;</code>
     */
    public boolean getBoolObj() {
      return boolObj_;
    }

    public static final int BYTESOBJ_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString bytesObj_;
    /**
     * <code>bytes bytesObj = 13;</code>
     */
    public com.google.protobuf.ByteString getBytesObj() {
      return bytesObj_;
    }

    public static final int FOLATOBJ_FIELD_NUMBER = 14;
    private float folatObj_;
    /**
     * <code>float folatObj = 14 [deprecated = true];</code>
     */
    @java.lang.Deprecated public float getFolatObj() {
      return folatObj_;
    }

    public static final int DOUBLEOBJ_FIELD_NUMBER = 15;
    private java.util.List<java.lang.Double> doubleObj_;
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     */
    public java.util.List<java.lang.Double>
        getDoubleObjList() {
      return doubleObj_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     */
    public int getDoubleObjCount() {
      return doubleObj_.size();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     */
    public double getDoubleObj(int index) {
      return doubleObj_.get(index);
    }
    private int doubleObjMemoizedSerializedSize = -1;

    public static final int INNERMESSAGE_FIELD_NUMBER = 16;
    private com.bupt.InnerMessageProtos.InnerMessage innerMessage_;
    /**
     * <code>.demo.InnerMessage innerMessage = 16;</code>
     */
    public boolean hasInnerMessage() {
      return innerMessage_ != null;
    }
    /**
     * <code>.demo.InnerMessage innerMessage = 16;</code>
     */
    public com.bupt.InnerMessageProtos.InnerMessage getInnerMessage() {
      return innerMessage_ == null ? com.bupt.InnerMessageProtos.InnerMessage.getDefaultInstance() : innerMessage_;
    }
    /**
     * <code>.demo.InnerMessage innerMessage = 16;</code>
     */
    public com.bupt.InnerMessageProtos.InnerMessageOrBuilder getInnerMessageOrBuilder() {
      return getInnerMessage();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getStrObjBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, strObj_);
      }
      if (int32Obj_ != 0) {
        output.writeInt32(2, int32Obj_);
      }
      if (int64Obj_ != 0L) {
        output.writeInt64(3, int64Obj_);
      }
      if (uint32Obj_ != 0) {
        output.writeUInt32(4, uint32Obj_);
      }
      if (uint64Obj_ != 0L) {
        output.writeUInt64(5, uint64Obj_);
      }
      if (sint32Obj_ != 0) {
        output.writeSInt32(6, sint32Obj_);
      }
      if (sint64Obj_ != 0L) {
        output.writeSInt64(7, sint64Obj_);
      }
      if (fixed32Obj_ != 0) {
        output.writeFixed32(8, fixed32Obj_);
      }
      if (fixed64Obj_ != 0L) {
        output.writeFixed64(9, fixed64Obj_);
      }
      if (sfixed32Obj_ != 0) {
        output.writeSFixed32(10, sfixed32Obj_);
      }
      if (sfixed64Obj_ != 0L) {
        output.writeSFixed64(11, sfixed64Obj_);
      }
      if (boolObj_ != false) {
        output.writeBool(12, boolObj_);
      }
      if (!bytesObj_.isEmpty()) {
        output.writeBytes(13, bytesObj_);
      }
      if (folatObj_ != 0F) {
        output.writeFloat(14, folatObj_);
      }
      if (getDoubleObjList().size() > 0) {
        output.writeUInt32NoTag(122);
        output.writeUInt32NoTag(doubleObjMemoizedSerializedSize);
      }
      for (int i = 0; i < doubleObj_.size(); i++) {
        output.writeDoubleNoTag(doubleObj_.get(i));
      }
      if (innerMessage_ != null) {
        output.writeMessage(16, getInnerMessage());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStrObjBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, strObj_);
      }
      if (int32Obj_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, int32Obj_);
      }
      if (int64Obj_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, int64Obj_);
      }
      if (uint32Obj_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, uint32Obj_);
      }
      if (uint64Obj_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, uint64Obj_);
      }
      if (sint32Obj_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(6, sint32Obj_);
      }
      if (sint64Obj_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(7, sint64Obj_);
      }
      if (fixed32Obj_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(8, fixed32Obj_);
      }
      if (fixed64Obj_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(9, fixed64Obj_);
      }
      if (sfixed32Obj_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(10, sfixed32Obj_);
      }
      if (sfixed64Obj_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(11, sfixed64Obj_);
      }
      if (boolObj_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, boolObj_);
      }
      if (!bytesObj_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, bytesObj_);
      }
      if (folatObj_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(14, folatObj_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getDoubleObjList().size();
        size += dataSize;
        if (!getDoubleObjList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        doubleObjMemoizedSerializedSize = dataSize;
      }
      if (innerMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, getInnerMessage());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bupt.MessageProtos.Message)) {
        return super.equals(obj);
      }
      com.bupt.MessageProtos.Message other = (com.bupt.MessageProtos.Message) obj;

      boolean result = true;
      result = result && getStrObj()
          .equals(other.getStrObj());
      result = result && (getInt32Obj()
          == other.getInt32Obj());
      result = result && (getInt64Obj()
          == other.getInt64Obj());
      result = result && (getUint32Obj()
          == other.getUint32Obj());
      result = result && (getUint64Obj()
          == other.getUint64Obj());
      result = result && (getSint32Obj()
          == other.getSint32Obj());
      result = result && (getSint64Obj()
          == other.getSint64Obj());
      result = result && (getFixed32Obj()
          == other.getFixed32Obj());
      result = result && (getFixed64Obj()
          == other.getFixed64Obj());
      result = result && (getSfixed32Obj()
          == other.getSfixed32Obj());
      result = result && (getSfixed64Obj()
          == other.getSfixed64Obj());
      result = result && (getBoolObj()
          == other.getBoolObj());
      result = result && getBytesObj()
          .equals(other.getBytesObj());
      result = result && (
          java.lang.Float.floatToIntBits(getFolatObj())
          == java.lang.Float.floatToIntBits(
              other.getFolatObj()));
      result = result && getDoubleObjList()
          .equals(other.getDoubleObjList());
      result = result && (hasInnerMessage() == other.hasInnerMessage());
      if (hasInnerMessage()) {
        result = result && getInnerMessage()
            .equals(other.getInnerMessage());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STROBJ_FIELD_NUMBER;
      hash = (53 * hash) + getStrObj().hashCode();
      hash = (37 * hash) + INT32OBJ_FIELD_NUMBER;
      hash = (53 * hash) + getInt32Obj();
      hash = (37 * hash) + INT64OBJ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInt64Obj());
      hash = (37 * hash) + UINT32OBJ_FIELD_NUMBER;
      hash = (53 * hash) + getUint32Obj();
      hash = (37 * hash) + UINT64OBJ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUint64Obj());
      hash = (37 * hash) + SINT32OBJ_FIELD_NUMBER;
      hash = (53 * hash) + getSint32Obj();
      hash = (37 * hash) + SINT64OBJ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSint64Obj());
      hash = (37 * hash) + FIXED32OBJ_FIELD_NUMBER;
      hash = (53 * hash) + getFixed32Obj();
      hash = (37 * hash) + FIXED64OBJ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFixed64Obj());
      hash = (37 * hash) + SFIXED32OBJ_FIELD_NUMBER;
      hash = (53 * hash) + getSfixed32Obj();
      hash = (37 * hash) + SFIXED64OBJ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSfixed64Obj());
      hash = (37 * hash) + BOOLOBJ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBoolObj());
      hash = (37 * hash) + BYTESOBJ_FIELD_NUMBER;
      hash = (53 * hash) + getBytesObj().hashCode();
      hash = (37 * hash) + FOLATOBJ_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getFolatObj());
      if (getDoubleObjCount() > 0) {
        hash = (37 * hash) + DOUBLEOBJ_FIELD_NUMBER;
        hash = (53 * hash) + getDoubleObjList().hashCode();
      }
      if (hasInnerMessage()) {
        hash = (37 * hash) + INNERMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getInnerMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bupt.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bupt.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bupt.MessageProtos.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bupt.MessageProtos.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bupt.MessageProtos.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bupt.MessageProtos.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bupt.MessageProtos.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bupt.MessageProtos.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bupt.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bupt.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bupt.MessageProtos.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Message)
        com.bupt.MessageProtos.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bupt.MessageProtos.internal_static_demo_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bupt.MessageProtos.internal_static_demo_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bupt.MessageProtos.Message.class, com.bupt.MessageProtos.Message.Builder.class);
      }

      // Construct using com.bupt.MessageProtos.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        strObj_ = "";

        int32Obj_ = 0;

        int64Obj_ = 0L;

        uint32Obj_ = 0;

        uint64Obj_ = 0L;

        sint32Obj_ = 0;

        sint64Obj_ = 0L;

        fixed32Obj_ = 0;

        fixed64Obj_ = 0L;

        sfixed32Obj_ = 0;

        sfixed64Obj_ = 0L;

        boolObj_ = false;

        bytesObj_ = com.google.protobuf.ByteString.EMPTY;

        folatObj_ = 0F;

        doubleObj_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
        if (innerMessageBuilder_ == null) {
          innerMessage_ = null;
        } else {
          innerMessage_ = null;
          innerMessageBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bupt.MessageProtos.internal_static_demo_Message_descriptor;
      }

      public com.bupt.MessageProtos.Message getDefaultInstanceForType() {
        return com.bupt.MessageProtos.Message.getDefaultInstance();
      }

      public com.bupt.MessageProtos.Message build() {
        com.bupt.MessageProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bupt.MessageProtos.Message buildPartial() {
        com.bupt.MessageProtos.Message result = new com.bupt.MessageProtos.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.strObj_ = strObj_;
        result.int32Obj_ = int32Obj_;
        result.int64Obj_ = int64Obj_;
        result.uint32Obj_ = uint32Obj_;
        result.uint64Obj_ = uint64Obj_;
        result.sint32Obj_ = sint32Obj_;
        result.sint64Obj_ = sint64Obj_;
        result.fixed32Obj_ = fixed32Obj_;
        result.fixed64Obj_ = fixed64Obj_;
        result.sfixed32Obj_ = sfixed32Obj_;
        result.sfixed64Obj_ = sfixed64Obj_;
        result.boolObj_ = boolObj_;
        result.bytesObj_ = bytesObj_;
        result.folatObj_ = folatObj_;
        if (((bitField0_ & 0x00004000) == 0x00004000)) {
          doubleObj_ = java.util.Collections.unmodifiableList(doubleObj_);
          bitField0_ = (bitField0_ & ~0x00004000);
        }
        result.doubleObj_ = doubleObj_;
        if (innerMessageBuilder_ == null) {
          result.innerMessage_ = innerMessage_;
        } else {
          result.innerMessage_ = innerMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bupt.MessageProtos.Message) {
          return mergeFrom((com.bupt.MessageProtos.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bupt.MessageProtos.Message other) {
        if (other == com.bupt.MessageProtos.Message.getDefaultInstance()) return this;
        if (!other.getStrObj().isEmpty()) {
          strObj_ = other.strObj_;
          onChanged();
        }
        if (other.getInt32Obj() != 0) {
          setInt32Obj(other.getInt32Obj());
        }
        if (other.getInt64Obj() != 0L) {
          setInt64Obj(other.getInt64Obj());
        }
        if (other.getUint32Obj() != 0) {
          setUint32Obj(other.getUint32Obj());
        }
        if (other.getUint64Obj() != 0L) {
          setUint64Obj(other.getUint64Obj());
        }
        if (other.getSint32Obj() != 0) {
          setSint32Obj(other.getSint32Obj());
        }
        if (other.getSint64Obj() != 0L) {
          setSint64Obj(other.getSint64Obj());
        }
        if (other.getFixed32Obj() != 0) {
          setFixed32Obj(other.getFixed32Obj());
        }
        if (other.getFixed64Obj() != 0L) {
          setFixed64Obj(other.getFixed64Obj());
        }
        if (other.getSfixed32Obj() != 0) {
          setSfixed32Obj(other.getSfixed32Obj());
        }
        if (other.getSfixed64Obj() != 0L) {
          setSfixed64Obj(other.getSfixed64Obj());
        }
        if (other.getBoolObj() != false) {
          setBoolObj(other.getBoolObj());
        }
        if (other.getBytesObj() != com.google.protobuf.ByteString.EMPTY) {
          setBytesObj(other.getBytesObj());
        }
        if (other.getFolatObj() != 0F) {
          setFolatObj(other.getFolatObj());
        }
        if (!other.doubleObj_.isEmpty()) {
          if (doubleObj_.isEmpty()) {
            doubleObj_ = other.doubleObj_;
            bitField0_ = (bitField0_ & ~0x00004000);
          } else {
            ensureDoubleObjIsMutable();
            doubleObj_.addAll(other.doubleObj_);
          }
          onChanged();
        }
        if (other.hasInnerMessage()) {
          mergeInnerMessage(other.getInnerMessage());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bupt.MessageProtos.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bupt.MessageProtos.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object strObj_ = "";
      /**
       * <code>string strObj = 1;</code>
       */
      public java.lang.String getStrObj() {
        java.lang.Object ref = strObj_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          strObj_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string strObj = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStrObjBytes() {
        java.lang.Object ref = strObj_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strObj_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string strObj = 1;</code>
       */
      public Builder setStrObj(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        strObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string strObj = 1;</code>
       */
      public Builder clearStrObj() {
        
        strObj_ = getDefaultInstance().getStrObj();
        onChanged();
        return this;
      }
      /**
       * <code>string strObj = 1;</code>
       */
      public Builder setStrObjBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        strObj_ = value;
        onChanged();
        return this;
      }

      private int int32Obj_ ;
      /**
       * <code>int32 int32Obj = 2;</code>
       */
      public int getInt32Obj() {
        return int32Obj_;
      }
      /**
       * <code>int32 int32Obj = 2;</code>
       */
      public Builder setInt32Obj(int value) {
        
        int32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 int32Obj = 2;</code>
       */
      public Builder clearInt32Obj() {
        
        int32Obj_ = 0;
        onChanged();
        return this;
      }

      private long int64Obj_ ;
      /**
       * <code>int64 int64Obj = 3;</code>
       */
      public long getInt64Obj() {
        return int64Obj_;
      }
      /**
       * <code>int64 int64Obj = 3;</code>
       */
      public Builder setInt64Obj(long value) {
        
        int64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 int64Obj = 3;</code>
       */
      public Builder clearInt64Obj() {
        
        int64Obj_ = 0L;
        onChanged();
        return this;
      }

      private int uint32Obj_ ;
      /**
       * <code>uint32 uint32Obj = 4;</code>
       */
      public int getUint32Obj() {
        return uint32Obj_;
      }
      /**
       * <code>uint32 uint32Obj = 4;</code>
       */
      public Builder setUint32Obj(int value) {
        
        uint32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 uint32Obj = 4;</code>
       */
      public Builder clearUint32Obj() {
        
        uint32Obj_ = 0;
        onChanged();
        return this;
      }

      private long uint64Obj_ ;
      /**
       * <code>uint64 uint64Obj = 5;</code>
       */
      public long getUint64Obj() {
        return uint64Obj_;
      }
      /**
       * <code>uint64 uint64Obj = 5;</code>
       */
      public Builder setUint64Obj(long value) {
        
        uint64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 uint64Obj = 5;</code>
       */
      public Builder clearUint64Obj() {
        
        uint64Obj_ = 0L;
        onChanged();
        return this;
      }

      private int sint32Obj_ ;
      /**
       * <code>sint32 sint32Obj = 6;</code>
       */
      public int getSint32Obj() {
        return sint32Obj_;
      }
      /**
       * <code>sint32 sint32Obj = 6;</code>
       */
      public Builder setSint32Obj(int value) {
        
        sint32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 sint32Obj = 6;</code>
       */
      public Builder clearSint32Obj() {
        
        sint32Obj_ = 0;
        onChanged();
        return this;
      }

      private long sint64Obj_ ;
      /**
       * <code>sint64 sint64Obj = 7;</code>
       */
      public long getSint64Obj() {
        return sint64Obj_;
      }
      /**
       * <code>sint64 sint64Obj = 7;</code>
       */
      public Builder setSint64Obj(long value) {
        
        sint64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 sint64Obj = 7;</code>
       */
      public Builder clearSint64Obj() {
        
        sint64Obj_ = 0L;
        onChanged();
        return this;
      }

      private int fixed32Obj_ ;
      /**
       * <code>fixed32 fixed32Obj = 8;</code>
       */
      public int getFixed32Obj() {
        return fixed32Obj_;
      }
      /**
       * <code>fixed32 fixed32Obj = 8;</code>
       */
      public Builder setFixed32Obj(int value) {
        
        fixed32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 fixed32Obj = 8;</code>
       */
      public Builder clearFixed32Obj() {
        
        fixed32Obj_ = 0;
        onChanged();
        return this;
      }

      private long fixed64Obj_ ;
      /**
       * <code>fixed64 fixed64Obj = 9;</code>
       */
      public long getFixed64Obj() {
        return fixed64Obj_;
      }
      /**
       * <code>fixed64 fixed64Obj = 9;</code>
       */
      public Builder setFixed64Obj(long value) {
        
        fixed64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 fixed64Obj = 9;</code>
       */
      public Builder clearFixed64Obj() {
        
        fixed64Obj_ = 0L;
        onChanged();
        return this;
      }

      private int sfixed32Obj_ ;
      /**
       * <code>sfixed32 sfixed32Obj = 10;</code>
       */
      public int getSfixed32Obj() {
        return sfixed32Obj_;
      }
      /**
       * <code>sfixed32 sfixed32Obj = 10;</code>
       */
      public Builder setSfixed32Obj(int value) {
        
        sfixed32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed32 sfixed32Obj = 10;</code>
       */
      public Builder clearSfixed32Obj() {
        
        sfixed32Obj_ = 0;
        onChanged();
        return this;
      }

      private long sfixed64Obj_ ;
      /**
       * <code>sfixed64 sfixed64Obj = 11;</code>
       */
      public long getSfixed64Obj() {
        return sfixed64Obj_;
      }
      /**
       * <code>sfixed64 sfixed64Obj = 11;</code>
       */
      public Builder setSfixed64Obj(long value) {
        
        sfixed64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed64 sfixed64Obj = 11;</code>
       */
      public Builder clearSfixed64Obj() {
        
        sfixed64Obj_ = 0L;
        onChanged();
        return this;
      }

      private boolean boolObj_ ;
      /**
       * <code>bool boolObj = 12;</code>
       */
      public boolean getBoolObj() {
        return boolObj_;
      }
      /**
       * <code>bool boolObj = 12;</code>
       */
      public Builder setBoolObj(boolean value) {
        
        boolObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool boolObj = 12;</code>
       */
      public Builder clearBoolObj() {
        
        boolObj_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesObj_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytesObj = 13;</code>
       */
      public com.google.protobuf.ByteString getBytesObj() {
        return bytesObj_;
      }
      /**
       * <code>bytes bytesObj = 13;</code>
       */
      public Builder setBytesObj(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bytesObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytesObj = 13;</code>
       */
      public Builder clearBytesObj() {
        
        bytesObj_ = getDefaultInstance().getBytesObj();
        onChanged();
        return this;
      }

      private float folatObj_ ;
      /**
       * <code>float folatObj = 14 [deprecated = true];</code>
       */
      @java.lang.Deprecated public float getFolatObj() {
        return folatObj_;
      }
      /**
       * <code>float folatObj = 14 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setFolatObj(float value) {
        
        folatObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float folatObj = 14 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder clearFolatObj() {
        
        folatObj_ = 0F;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> doubleObj_ = java.util.Collections.emptyList();
      private void ensureDoubleObjIsMutable() {
        if (!((bitField0_ & 0x00004000) == 0x00004000)) {
          doubleObj_ = new java.util.ArrayList<java.lang.Double>(doubleObj_);
          bitField0_ |= 0x00004000;
         }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public java.util.List<java.lang.Double>
          getDoubleObjList() {
        return java.util.Collections.unmodifiableList(doubleObj_);
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public int getDoubleObjCount() {
        return doubleObj_.size();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public double getDoubleObj(int index) {
        return doubleObj_.get(index);
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public Builder setDoubleObj(
          int index, double value) {
        ensureDoubleObjIsMutable();
        doubleObj_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public Builder addDoubleObj(double value) {
        ensureDoubleObjIsMutable();
        doubleObj_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public Builder addAllDoubleObj(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureDoubleObjIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, doubleObj_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public Builder clearDoubleObj() {
        doubleObj_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
        return this;
      }

      private com.bupt.InnerMessageProtos.InnerMessage innerMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bupt.InnerMessageProtos.InnerMessage, com.bupt.InnerMessageProtos.InnerMessage.Builder, com.bupt.InnerMessageProtos.InnerMessageOrBuilder> innerMessageBuilder_;
      /**
       * <code>.demo.InnerMessage innerMessage = 16;</code>
       */
      public boolean hasInnerMessage() {
        return innerMessageBuilder_ != null || innerMessage_ != null;
      }
      /**
       * <code>.demo.InnerMessage innerMessage = 16;</code>
       */
      public com.bupt.InnerMessageProtos.InnerMessage getInnerMessage() {
        if (innerMessageBuilder_ == null) {
          return innerMessage_ == null ? com.bupt.InnerMessageProtos.InnerMessage.getDefaultInstance() : innerMessage_;
        } else {
          return innerMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>.demo.InnerMessage innerMessage = 16;</code>
       */
      public Builder setInnerMessage(com.bupt.InnerMessageProtos.InnerMessage value) {
        if (innerMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          innerMessage_ = value;
          onChanged();
        } else {
          innerMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.demo.InnerMessage innerMessage = 16;</code>
       */
      public Builder setInnerMessage(
          com.bupt.InnerMessageProtos.InnerMessage.Builder builderForValue) {
        if (innerMessageBuilder_ == null) {
          innerMessage_ = builderForValue.build();
          onChanged();
        } else {
          innerMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.demo.InnerMessage innerMessage = 16;</code>
       */
      public Builder mergeInnerMessage(com.bupt.InnerMessageProtos.InnerMessage value) {
        if (innerMessageBuilder_ == null) {
          if (innerMessage_ != null) {
            innerMessage_ =
              com.bupt.InnerMessageProtos.InnerMessage.newBuilder(innerMessage_).mergeFrom(value).buildPartial();
          } else {
            innerMessage_ = value;
          }
          onChanged();
        } else {
          innerMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.demo.InnerMessage innerMessage = 16;</code>
       */
      public Builder clearInnerMessage() {
        if (innerMessageBuilder_ == null) {
          innerMessage_ = null;
          onChanged();
        } else {
          innerMessage_ = null;
          innerMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.demo.InnerMessage innerMessage = 16;</code>
       */
      public com.bupt.InnerMessageProtos.InnerMessage.Builder getInnerMessageBuilder() {
        
        onChanged();
        return getInnerMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.demo.InnerMessage innerMessage = 16;</code>
       */
      public com.bupt.InnerMessageProtos.InnerMessageOrBuilder getInnerMessageOrBuilder() {
        if (innerMessageBuilder_ != null) {
          return innerMessageBuilder_.getMessageOrBuilder();
        } else {
          return innerMessage_ == null ?
              com.bupt.InnerMessageProtos.InnerMessage.getDefaultInstance() : innerMessage_;
        }
      }
      /**
       * <code>.demo.InnerMessage innerMessage = 16;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bupt.InnerMessageProtos.InnerMessage, com.bupt.InnerMessageProtos.InnerMessage.Builder, com.bupt.InnerMessageProtos.InnerMessageOrBuilder> 
          getInnerMessageFieldBuilder() {
        if (innerMessageBuilder_ == null) {
          innerMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bupt.InnerMessageProtos.InnerMessage, com.bupt.InnerMessageProtos.InnerMessage.Builder, com.bupt.InnerMessageProtos.InnerMessageOrBuilder>(
                  getInnerMessage(),
                  getParentForChildren(),
                  isClean());
          innerMessage_ = null;
        }
        return innerMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:demo.Message)
    }

    // @@protoc_insertion_point(class_scope:demo.Message)
    private static final com.bupt.MessageProtos.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bupt.MessageProtos.Message();
    }

    public static com.bupt.MessageProtos.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public com.bupt.MessageProtos.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\004demo\032\022InnerMessage.prot" +
      "o\"\325\002\n\007Message\022\016\n\006strObj\030\001 \001(\t\022\020\n\010int32Ob" +
      "j\030\002 \001(\005\022\020\n\010int64Obj\030\003 \001(\003\022\021\n\tuint32Obj\030\004" +
      " \001(\r\022\021\n\tuint64Obj\030\005 \001(\004\022\021\n\tsint32Obj\030\006 \001" +
      "(\021\022\021\n\tsint64Obj\030\007 \001(\022\022\022\n\nfixed32Obj\030\010 \001(" +
      "\007\022\022\n\nfixed64Obj\030\t \001(\006\022\023\n\013sfixed32Obj\030\n \001" +
      "(\017\022\023\n\013sfixed64Obj\030\013 \001(\020\022\017\n\007boolObj\030\014 \001(\010" +
      "\022\020\n\010bytesObj\030\r \001(\014\022\024\n\010folatObj\030\016 \001(\002B\002\030\001" +
      "\022\025\n\tdoubleObj\030\017 \003(\001B\002\020\001\022(\n\014innerMessage\030" +
      "\020 \001(\0132\022.demo.InnerMessageB\036\n\010com.buptB\rM",
      "essageProtosH\001\210\001\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bupt.InnerMessageProtos.getDescriptor(),
        }, assigner);
    internal_static_demo_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Message_descriptor,
        new java.lang.String[] { "StrObj", "Int32Obj", "Int64Obj", "Uint32Obj", "Uint64Obj", "Sint32Obj", "Sint64Obj", "Fixed32Obj", "Fixed64Obj", "Sfixed32Obj", "Sfixed64Obj", "BoolObj", "BytesObj", "FolatObj", "DoubleObj", "InnerMessage", });
    com.bupt.InnerMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
